### ISSUE TITLE
feature: put organization specific envs into pg

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#686]
- [ ] cleanup: remove feeling lucky button

### Server ENV's

- [ ] `S3_BUCKET`
- [ ] `DOCUMENT_UPLOAD_FEATURE`
- [ ] `DOCUMENT_DOWNLOAD_FEATURE`
- [ ] `ONLY_ADMIN_CAN_CREATE_CARDS`
- [ ] `RAG_PROMPT`
- [ ] `N_RETRIEVALS_TO_INCLUDE`
- [ ] `ALWAYS_REQUIRE_AUTH`
- [ ] `ADMIN_USER_EMAIL`
- [ ] `ADMIN_USER_PASSWORD`
- [ ] `DUPLICATE_DISTANCE_THRESHOLD`
- [ ] `OPENAI_BASE_URL`
- [ ] `EMBEDDING_SIZE`
- [ ] `USE_EMBED_SERVER`
- [ ] `PARSER_COMMAND`
- [ ] `EMBEDDING_SERVER_CALL`

### Search ENV's

- [ ] `PUBLIC_API_HOST`
- [ ] `PLAUSIBLE_HOST`
- [ ] `PUBLIC_CREATE_EVIDENCE_FEATURE`
- [ ] `PUBLIC_DOCUMENT_UPLOAD_FEATURE`
- [ ] `PUBLIC_SEARCH_QUERIES`
- [ ] `PUBLIC_FRONTMATTER_VALS`
- [ ] `PUBLIC_LINES_BEFORE_SHOW_MORE`
- [ ] `PUBLIC_SHOW_GITHUB_STARS`
- [ ] `DATASET`
- [ ] `OG_DESCRIPTION`
- [ ] `PUBLIC_ALWAYS_REQUIRE_AUTH`
- [ ] `PUBLIC_IMAGE_RANGE_START_KEY`
- [ ] `PUBLIC_IMAGE_RANGE_END_KEY`
- [ ] `PUBLIC_DATE_RANGE_VALUE`
- [ ] `PUBLIC_FILTER_ITEMS`
- [ ] `SUGGESTED_QUERIES`
- [ ] `PUBLIC_SEARCH_VOTE_FEATURE`

**Comment by fastfists** [comment]
Most if not all of these configuration variables should actually be on the DATASET level and not on the ORG level. Updating list as follows 

### Server

- [ ] `EMBEDDING_SIZE` : 1536 (Hard locked for now)
- [ ] `DOCUMENT_UPLOAD_FEATURE`
- [ ] `DOCUMENT_DOWNLOAD_FEATURE`
- [ ] `OPENAI_BASE_URL`
- [ ] ` RAG_PROMPT`
- [ ] `N_RETRIEVALS_TO_INCLUDE`
- [ ] `DUPLICATE_DISTANCE_THRESHOLD`
- [ ] ~~`ALWAYS_REQUIRE_AUTH`~~  Removing because of advanced user integration
- [ ] ~~`ADMIN_USER_EMAIL`~~ Removing because of advanced user integration
- [ ] ~~`ADMIN_USER_PASSWORD`~~ Removing because of advanced user integration
- [ ] ~~`S3_BUCKET`~~ Removing because we will manage this.

### Search

- [ ] `PUBLIC_API_HOST`
- [ ] ~~`PLAUSIBLE_HOST`~~ Not sure what to do about this, but doesn't belong on our dashboard
- [ ] `PUBLIC_CREATE_EVIDENCE_FEATURE`
- [ ] `PUBLIC_DOCUMENT_UPLOAD_FEATURE`
- [ ] `PUBLIC_SEARCH_QUERIES`
- [ ] `PUBLIC_FRONTMATTER_VALS`
- [ ] `PUBLIC_LINES_BEFORE_SHOW_MORE`
- [ ] `PUBLIC_SHOW_GITHUB_STARS`
- [ ] `DATASET`
- [ ] `OG_DESCRIPTION`
- [ ] ~~`PUBLIC_ALWAYS_REQUIRE_AUTH`~~ Removing due to more advanced user integration
- [ ] `PUBLIC_IMAGE_RANGE_START_KEY` ??? Should we keep?
- [ ] `PUBLIC_IMAGE_RANGE_END_KEY` ??? Should we keep?
- [ ] `PUBLIC_DATE_RANGE_VALUE`
- [ ] `PUBLIC_FILTER_ITEMS`
- [ ] `SUGGESTED_QUERIES`
- [ ] `PUBLIC_SEARCH_VOTE_FEATURE`
